DROP TABLE DATABASECHANGELOG;
DROP TABLE DATABASECHANGELOGLOCK;
DROP TABLE report_test;
DROP TABLE report_items;
DROP TABLE reports;
DROP TABLE endpoint_headers;
DROP TABLE endpoint_parameters;
DROP TABLE endpoint_versions;
DROP TABLE endpoints;
DROP TABLE application_environments;
DROP TABLE applications;
DROP TABLE documenter_groups_membership;
DROP TABLE documenter_groups_requests;
DROP TABLE documenter_groups;
SHOW TABLES;