databaseChangeLog:
  - changeSet:
      id: create_application_environments_table
      author: Coleman
      changes:
        - createTable:
            tableName: application_environments
            columns:
              - column:
                  name: id
                  type: int
                  autoIncrement: true
                  constraints:
                    primaryKey: true
                    nullable: false
              - column:
                  name: application_id
                  type: int
                  constraints:
                    onDelete: CASCADE
                    foreignKeyName: fk_environment_id_application_id
                    referencedColumnNames: id
                    referencedTableName: applications
              - column:
                  name: environment_name
                  type: varchar(128)
              - column:
                  name: environment_proxy
                  type: int
              - column:
                  name: environment_description
                  type: mediumtext
              - column:
                  name: environment_address
                  type: varchar(1024)
